const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Zumo",
      rating: 4.5,
      numReviews: 5,
      countInStock: 3,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "gold-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants2",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 78,
      brand: "Zara",
      rating: 4.1,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants2",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 78,
      brand: "Casely",
      rating: 4.1,
      numReviews: 10,
      countInStock: 0,
      description: "Smart looking pants+2",
    },
  ],
};

export default data;
